name: infrastructure
on: 
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - .github/workflows/azure-infrastructure.yaml
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: terraform-init
        run: |
          terraform -chdir="${{ github.workspace }}/infrastructure" init /
                    --backend-config="${{ github.workspace }}/infrastructure/config.tfbackend" /
                    --backend-config="key=infrastructure.tfstate"
          

      - name: terraform-apply
        run: |
          terraform -chdir="${{ github.workspace }}/infrastructure" apply /
                    --auto-approve            

 